name: "ðŸ—‚ Version Change"
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (no 'v' prefix)"
        required: true

jobs:
  create_version_pull_request:
    name: "ðŸ—‚ Create Version Pull Request"
    runs-on: ubuntu-latest
    steps:
      - name: "ðŸ§¾ Checkout"
        uses: actions/checkout@v4

      - name: "ðŸ“ Change Version"
        uses: vers-one/dotnet-project-version-updater@v1.7
        with:
          file: "Stranne.EcsMemory.Game/Stranne.EcsMemory.Game.csproj"
          version: ${{ github.event.inputs.version }}

      - name: "â¤´ï¸ Create Pull Request"
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: version/${{ github.event.inputs.version }}
          commit-message: >
            update version to ${{ github.event.inputs.version }}
          title: >
            "chore: update version to
            ${{ github.event.inputs.version }}"
          body: >
            chore: update the version to
            ${{ github.event.inputs.version }}.
